stages:
  - test

gitleaks_scan_job:
  stage: test
  tags:
    - shared
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""] 
  script:
    - echo "Сканирования Secret Detection by Gitleaks..."
    - gitleaks detect --no-git -v --config gitleaks-orig.toml --report-format json --report-path gitleaks-report.json
  artifacts:
    paths:
      - gitleaks-report.json
    when: always 
    expire_in: 1 week
  allow_failure: true
